// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniversalAPIGateway.Infrastructure.Persistence;

#nullable disable

namespace UniversalAPIGateway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260221223137_AddOperationalIndexes")]
    partial class AddOperationalIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ApiClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RateLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("ClientName")
                        .IsUnique();

                    b.ToTable("ApiClients", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ClientUsageStatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RequestsCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId", "PeriodStart", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("ClientUsageStats", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.GatewayRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("GatewayRequests", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.GatewayResponseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<long>("TokenUsage")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RequestId");

                    b.HasIndex("ProviderId", "CreatedAt");

                    b.HasIndex("RequestId", "CreatedAt");

                    b.ToTable("GatewayResponses", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderCooldownEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DisabledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DisabledUntil");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderCooldowns", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderFailureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId", "OccurredAt");

                    b.ToTable("ProviderFailures", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderHealthEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvgLatency")
                        .HasColumnType("integer");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SuccessRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LastChecked");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId", "LastChecked");

                    b.ToTable("ProviderHealth", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<long>("QuotaLimit")
                        .HasColumnType("bigint");

                    b.Property<long>("QuotaUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("ResetPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId", "IsActive");

                    b.ToTable("ProviderKeys", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderPerformanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvgLatency")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QualityScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("SuccessRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TaskType");

                    b.HasIndex("ProviderId", "TaskType")
                        .IsUnique();

                    b.ToTable("ProviderPerformance", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderScoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TaskType");

                    b.HasIndex("ProviderId", "TaskType")
                        .IsUnique();

                    b.ToTable("ProviderScores", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderTelemetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Tokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("TaskType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ProviderId", "Timestamp");

                    b.HasIndex("ProviderId", "TaskType", "Timestamp");

                    b.ToTable("ProviderTelemetry", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.RoutingDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateProviders")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ChosenProviderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DecisionScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChosenProviderId");

                    b.HasIndex("RequestId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ChosenProviderId", "Timestamp");

                    b.ToTable("RoutingDecisions", (string)null);
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ClientUsageStatEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ApiClientEntity", "Client")
                        .WithMany("UsageStats")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.GatewayResponseEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("GatewayResponses")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.GatewayRequestEntity", "Request")
                        .WithMany("Responses")
                        .HasForeignKey("RequestId")
                        .HasPrincipalKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderCooldownEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("Cooldowns")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderFailureEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("Failures")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderHealthEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("HealthChecks")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderKeyEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("ProviderKeys")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderPerformanceEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("Performances")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderScoreEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("Scores")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderTelemetryEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "Provider")
                        .WithMany("Telemetry")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.RoutingDecisionEntity", b =>
                {
                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", "ChosenProvider")
                        .WithMany("RoutingDecisions")
                        .HasForeignKey("ChosenProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniversalAPIGateway.Infrastructure.Persistence.Entities.GatewayRequestEntity", "Request")
                        .WithMany("RoutingDecisions")
                        .HasForeignKey("RequestId")
                        .HasPrincipalKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenProvider");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ApiClientEntity", b =>
                {
                    b.Navigation("UsageStats");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.GatewayRequestEntity", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("RoutingDecisions");
                });

            modelBuilder.Entity("UniversalAPIGateway.Infrastructure.Persistence.Entities.ProviderEntity", b =>
                {
                    b.Navigation("Cooldowns");

                    b.Navigation("Failures");

                    b.Navigation("GatewayResponses");

                    b.Navigation("HealthChecks");

                    b.Navigation("Performances");

                    b.Navigation("ProviderKeys");

                    b.Navigation("RoutingDecisions");

                    b.Navigation("Scores");

                    b.Navigation("Telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
